version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - ./themes/:/var/www/html/wp-content/themes/
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
